
const categories = {
    development: {
        slug: "developpement",
        sections: [
            "Adobe Flash",
            "Adobe Flex",
            "Agile / Scrum",
            "Android",
            "Angular",
            "AngularJS",
            "Apache Cordova",
            "API",
            "Application Meta",
            "Application mobile",
            "Arduino",
            "ASP.NET",
            "Aurelia",
            "Backbone.js",
            "Back-end",
            "Base de données",
            "Blockchain",
            "C",
            "C#",
            "C++",
            "Coldfusion",
            "Cryptomonnaie",
            "Delphi",
            "Django",
            "Docker",
            "Ember.js",
            "Fortran",
            "Front-end",
            "Full-stack",
            "Gestion de projet",
            "Ionic",
            "iOS",
            "IoT",
            "Jakarta EE",
            "Java",
            "JavaScript",
            "Jeux vidéo",
            "jQuery",
            "JSP",
            "Laravel",
            "Linux",
            "Lua",
            "macOS",
            "MATLAB",
            "MySQL",
            ".NET",
            "NFT",
            "Node.js",
            "Perl",
            "PHP",
            "Python",
            "R",
            "React",
            "Ruby on Rails",
            "Smartwatches",
            "Symfony",
            "Système embarqué",
            "Visual Basic",
            "Vue.JS",
            "Windev, Webdev",
            "Windows",
            "Xamarin",
            "Zend"
        ]
    },
    web: {
        slug: "web",
        sections: [
            "Admin système, sécurité",
            "Autres CMS",
            "Création de site internet",
            "CSS, HTML, XML",
            "Développement spécifique",
            "Drupal",
            "Experience utilisateur",
            "Gestion site web",
            "Installation de Script",
            "Integration HTML",
            "Joomla",
            "Landing page",
            "Migration ou refonte de site",
            "Modules et composants",
            "Rédaction",
            "Relecture, correction",
            "SaaS",
            "Site clé en main",
            "Spip",
            "Wix",
            "WordPress"
        ]
    },
    ecommerce: {
        slug: "e-commerce",
        sections: [
            "Dropshipping",
            "Drupal Commerce",
            "Magento",
            "Mangopay",
            "Marketplace",
            "Opencart",
            "Oscommerce",
            "Paypal",
            "Prestashop",
            "Shopify",
            "Site E-commerce",
            "Stripe",
            "Système de paiement",
            "Ubercart",
            "Virtuemart",
            "WooCommerce",
            "Zencart"
        ]
    },
    graphics: {
        slug: "graphisme",
        sections: [
            "Animation 3D",
            "Audio, Video, Multimedia",
            "Bannière",
            "Boutons",
            "CAO",
            "Charte graphique",
            "DAO",
            "Dessin industriel",
            "Logo",
            "Mise en page",
            "Motion design",
            "Photo",
            "Photoshop",
            "Print (flyer, plaquette, affiche...)"
        ]
    },
    company_system: {
        slug: "systemes-d-entreprise",
        sections: [
            "Administration",
            "AWS",
            "Cloud computing",
            "CRM",
            "Data mining",
            "E-learning",
            "ERP",
            "ETL",
            "Gestion de documents (GED)",
            "Infogérance",
            "Infrastructure et réseaux",
            "Logiciel",
            "Maintenance",
            "Matériel",
            "Migration",
            "Progiciels",
            "Sécurité",
            "Stockage et sauvegarde",
            "Téléphonie et Télécom",
            "Test, recette, qualification"
        ]
    },
    services: {
        slug: "services",
        sections: [
            "Assistance juridique",
            "Assistant virtuel",
            "Communication",
            "Comptabilité",
            "Création ou conversion ebook",
            "Data entry",
            "Etude de marché",
            "Formation",
            "Prospection commerciale",
            "Publicité",
            "Relations presse",
            "Ressources humaines",
            "Secrétariat à domicile",
            "Télémarketing",
            "Traduction"
        ]
    }
}

module.exports = { categories };